services:
  # API Gateway - Traefik
  traefik:
    image: traefik:v2.10
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080" # Traefik dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - quantum_network

  # Next.js Web App
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    command: npm run dev
    volumes:
      - ./apps/web:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://traefik
    ports:
      - "3000:3000"
    networks:
      - quantum_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`localhost`)"
      - "traefik.http.routers.web.priority=1"
      - "traefik.http.services.web.loadbalancer.server.port=3000"
    
  # Auth Service
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    volumes:
      - ./services/auth:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/quantum_auth
    depends_on:
      - postgres
    networks:
      - quantum_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=Host(`localhost`) && PathPrefix(`/api`)"
      - "traefik.http.routers.auth.priority=10" # Higher priority than web
      - "traefik.http.middlewares.auth-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.auth.middlewares=auth-stripprefix"
      - "traefik.http.services.auth.loadbalancer.server.port=8000"

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quantum_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - quantum_network

  # Note: Supabase Studio commented out for now - will be added in a later phase
  # when full Supabase stack is configured

networks:
  quantum_network:
    driver: bridge

volumes:
  postgres_data:
